name: check_bun

on:
  push:
    branches:
      - "main"
  pull_request:
  schedule:
    - cron: "0 8 * * FRI" # 17:00, every friday on JST
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        bun-version:
          - "canary"
          - "latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}
      - name: Show environment
        run: set -x; pwd; ls -la; bun --version;
      - name: Run test
        run: bun ./src/test/index_bun.ts
