name: check_code

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Show environment
        run: set -x; pwd; ls -la; deno --version;
      - name: Check
        run: deno task check
      - name: Lint
        run: deno task lint
      - name: Format
        run: deno task format
      - name: Test
        run: deno task test
      - name: Build
        run: deno task build
