name: check_code

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup volta
        uses: volta-cli/action@v4
      - name: Show environment
        run: set -x; pwd; ls -la; node -v; npm -v;
      - name: Install
        run: npm install
      - name: Check
        run: npm run check
