name: check_node

on:
  push:
    branches:
      - "main"
  pull_request:
  schedule:
    - cron: "0 8 * * FRI" # 17:00, every friday on JST
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node-version:
          - "18"
          - "20"
          - "22"
          - "latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Show environment
        run: set -x; pwd; ls -la; node -v; npm -v;
      - name: Install
        run: npm install
      - name: Pack tarball
        run: |
          npm run build
          npm pack
      - name: Run test with packed tarball
        run: |
          TARBALL="$(ls -1 mryhryki-simple-encryption-*.tgz | head -n 1)"
          npm install "./${TARBALL}"
          npm run build:test
          node src/test/index_node.js
