name: check_deno

on:
  push:
    branches:
      - "main"
  pull_request:
  schedule:
    - cron: "0 8 * * FRI" # 17:00, every friday on JST
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        deno-version:
          - "v2.x"
          - "v1.x"
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Show environment
        run: set -x; pwd; ls -la; deno --version;
      - name: Run test
        run: deno run ./src/test/index_deno.ts
