name: check_node18

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Update npm
        run: npm install -g npm
      - name: Show environment
        run: set -x; pwd; ls -la; node -v; npm -v;
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: node -r esbuild-register ./src/test/index_node.ts
