name: check_bun

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.x
      - name: Show environment
        run: set -x; pwd; ls -la; bun --version;
      - name: Run test
        run: bun ./src/test/index_bun.ts
