name: check_deno

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Show environment
        run: set -x; pwd; ls -la; deno --version;
      - name: Run test
        run: deno run ./src/test/index_deno.ts
