name: check_code

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Show environment
        run: set -x; pwd; ls -la; node -v; npm -v;
      - name: Install dependencies
        run: npm install

      # TODO: Remove next step
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Check
        run: deno check ./src/test/index.ts
      - name: Lint
        run: npm run lint
        run: deno check ./src/index.ts
      - name: Format
        run: deno fmt ./src/
      - name: Test
        run: deno test ./src/
