name: check

on: push

jobs:
  check_pull_request:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Update npm
        run: npm install -g npm

      - name: Show environment
        run: set -x; pwd; ls -la; node -v; npm -v; deno --version; bun --version;

      - name: Test
        run: npm test
      - name: Check
        run: npm run check
      - name: Format
        run: npm run fmt

      - name: Run on Node.js
        run: echo "TODO"
      - name: Run on Deno
        run: echo "TODO"
      - name: Run on Bun
        run: echo "TODO"
