name: check_node

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node-version:
          - 16
          - 18
          - 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Show environment
        run: set -x; pwd; ls -la; node -v; npm -v;
      - name: Run test with packed tarball
        run: |
          set -xe
          npm pack
          TARBALL="$(ls -1 mryhryki-simple-encryption-*.tgz | head -n 1)"
          npm install "./${TARBALL}"
          ./node_modules/.bin/esbuild --bundle --platform=node --outfile=./dist/test.js ./src/test/index_node_with_packed_tarball.ts
          cat ./dist/test.js | node --input-type=commonjs
