name: publish_to_npm

on:
  workflow_dispatch:
    inputs:
      bump_type:
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Show environment
        run: set -x; pwd; ls -la; node -v; npm -v;
      - name: Run npm install
        run: npm install
      - name: Set branch name
        run: |
          echo "BRANCH=bump-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git switch -c "${BRANCH}"
      - name: Update version
        run: npm version ${{ github.event.inputs.bump_type }}
      - name: Set AuthToken for npmjs.com
        run: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > "${HOME}/.npmrc"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Create Pull Request
        run: |
          git push origin "${BRANCH}"
          gh pr create --title "Bump ${{ github.event.inputs.bump_type }} version" --body "x" --reviewer "mryhryki"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Publish to npmjs.com
        run: npm publish
      - name: Push tag
        run: git push --tags
