name: release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        required: true
        description: 'Bump type'
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # This setting is required to push contents and tags by git for main branch
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Show environment
        run: set -x; pwd; ls -la; node -v; npm -v;

      # Release
      - name: Setup Git
        run: |
          git config user.name "mryhryki"
          git config user.email "mryhryki@gmail.com"
      - name: Set AuthToken for npmjs.com
        run: echo "//registry.npmjs.org/:_authToken=${NPM_ACCESS_TOKEN}" > "${HOME}/.npmrc"
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - name: Update package version
        run: |
          npm version ${{ github.event.inputs.bump_type }}
          echo VERSION="v$(cat package.json | jq -r '.version')" >> "${GITHUB_ENV}"
      - name: Publish to npmjs.com
        run: |
          npm run prepare
          npm publish
      - name: Push tag to GitHub
        run: |
          git push
          git push --tags
      - name: Create Release to GitHub
        run: gh release create "${VERSION}" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
