name: release_github

on:
  push:
    branches:
      - main
    paths:
      - "package.json"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check default branch
        run: |
          if [[ "${GITHUB_REF_NAME}" != "main" ]]; then
            echo "This action only runs on the main branch."
            exit 1
          fi
      - name: Checkout
        uses: actions/checkout@v5
      - name: Check that version in package.json has changed
        id: check
        run: |
          VERSION_OF_PACKAGE_JSON="v$(jq -r '.version' package.json)"
          echo "${VERSION_OF_PACKAGE_JSON}"
          VERSION_OF_GITHUB_RELEASE="$(gh release view --json tagName | jq -r .tagName)"
          echo "${VERSION_OF_GITHUB_RELEASE}"
          if [[ "v${VERSION_OF_PACKAGE_JSON}" == "${VERSION_OF_GITHUB_RELEASE}" ]]; then
            echo "No changes"
          else
            echo "changed=true" >> "${GITHUB_OUTPUT}"
          fi
      - name: Create Release to GitHub
        if: ${{ steps.check.outputs.changed == 'true' }}
        run: gh release create "v$(jq -r '.version' package.json)" --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
