name: release_pull_request

on:
  workflow_dispatch:
    inputs:
      bump_type:
        required: true
        description: 'Bump type'
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
      - name: Update npm
        run: npm install -g npm@latest
      - name: Install
        run: npm install
      - name: Check
        run: npm run check
      - name: Setup Git
        run: |
          git config user.name "mryhryki"
          git config user.email "mryhryki@gmail.com"
      - name: Update package version
        id: update_version
        run: |
          npm version ${{ github.event.inputs.bump_type }}
          echo "version=v$(jq -r '.version' package.json)" >> "${GITHUB_OUTPUT}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          title: "Release ${{ steps.update_version.outputs.version }}"
          commit-message: "Release ${{ steps.update_version.outputs.version }}"
          branch: "release"
          branch-suffix: timestamp
          delete-branch: true
          assignees: mryhryki
          reviewers: mryhryki
