name: release_pull_request

on:
  workflow_dispatch:
    inputs:
      bump_type:
        required: true
        description: 'Bump type'
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24
      - name: Update npm
        run: npm install -g npm@latest
      - name: Install
        run: npm install
      - name: Check
        run: npm run check
      - name: Setup Git
        run: |
          git config user.name "mryhryki"
          git config user.email "mryhryki@gmail.com"
      - name: Update package version
        run: npm version ${{ github.event.inputs.bump_type }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Release ${{ steps.update_version.outputs.version }}"
          commit-message: "Release ${{ steps.update_version.outputs.version }}"
          branch: "release"
          branch-suffix: timestamp
          delete-branch: true
          assignees: mryhryki
          reviewers: mryhryki
