name: release_npmjs

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24
      - name: Update npm
        run: npm install -g npm@latest
      - name: Install
        run: npm install
      - name: Check
        run: npm run check
      - name: Publish to npmjs.com
        run: |
          npm run build
          npm publish
