name: release_npmjs

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check tag name
        run: |
          if [[ "${GITHUB_REF_TYPE}" != "tag" ]]; then
            echo "This action only runs on tag events: ${GITHUB_REF_TYPE}"
            exit 1
          fi
          TAG_NAME=$(echo "${GITHUB_REF_NAME}" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$')
          if [[ "${TAG_NAME}" == "" ]]; then
            echo "Invalid tag name: ${GITHUB_REF_NAME}"
            exit 1
          fi
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24
      - name: Update npm
        run: npm install -g npm@latest
      - name: Install
        run: npm install
      - name: Check
        run: npm run check
      - name: Publish to npmjs.com
        run: |
          npm run build
          npm publish
