name: release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        required: true
        description: 'Bump type'
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Update npm
        run: npm install -g npm@latest
      - name: Show environment
        run: set -x; pwd; ls -la; node -v; npm -v;
      - name: Install
        run: npm install
      - name: Check
        run: npm run check

      # Release
      - name: Setup Git
        run: |
          git config user.name "mryhryki"
          git config user.email "mryhryki@gmail.com"
      - name: Update package version
        run: |
          npm version ${{ github.event.inputs.bump_type }}
          echo VERSION="v$(cat package.json | jq -r '.version')" >> "${GITHUB_ENV}"
      - name: Publish to npmjs.com
        run: |
          npm run build
          npm publish
      - name: Push tag to GitHub
        run: |
          git push
          git push --tags
      - name: Create Release to GitHub
        run: gh release create "${VERSION}" --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
