name: update_packages

on:
  schedule:
    - cron: "15 11 20 3,7,11 *" # UTC
  workflow_dispatch:

jobs:
  update_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Update packages
        run: |
          npm i -g npm
          npm exec -- npm-check-updates -u
          npm install
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Update package.json"
          commit-message: "Update package.json"
          branch: "update-packages"
          delete-branch: true
          branch-suffix: timestamp
          assignees: mryhryki
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
